version: '2.2'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Порт снаружи:порт внутри контейнера
    environment:
      - NODE_ENV=production
    restart: unless-stopped
