export enum PATHS {
  HOME = '/',
  LOGIN = '/login',
  NOT_FOUND = '/404',
  INSTALLMENT = '/installment',
  BUSINESS = '/business',
  CUSTOMERS = '/customers',
  DELIVERY = '/delivery',
  RETURNS = '/returns',
  HELP = '/help',
  CONTACTS = '/contacts',

  PRODUCTS = '/products',
  FAVORITES = '/favorites',
  ACCOUNT = '/account',
  BASKET = '/basket',
  PROFILE = '/profile',
  COMPARE = '/compare',
  ORDERS = '/orders',

  DISCOUNTS = '/discounts',
  APARTMENT = '/apartment-giveaway',
  COFFEE = '/coffee-promo',
  BIKES = '/bikes',
  BELARUSIAN = '/belarusian',
  VET = '/vet',
  FRIDGES = '/fridges',
  TV = '/tv',
  SMARTPHONES = '/smartphones',
  VACUUM = '/vacuum',
  SOFAS = '/sofas',
  
  ALL = '*',
}
